# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.5


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [2]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [3]:
import numpy as np
array = np.arange(1000000)
lista = list(range(1000000))

print('Performance Array:')
%time for _ in range(10): array2 = array * 2
print('Performance Lista:')
%time for _ in range(10): lista2 = [x * 2 for x in lista]

Performance Array:
Wall time: 26.1 ms
Performance Lista:
Wall time: 1.43 s


### Exercício 2

In [4]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [5]:
import numpy as np
array = np.arange(10)
print('10 elementos do array:')
array

10 elementos do array:


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print('Alteração dos valores de todos os elementos dos índices 5 a 8 para 0:')
array[5:8] = 0
array

Alteração dos valores de todos os elementos dos índices 5 a 8 para 0:


array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [7]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [8]:
import numpy as np
array_3d = np.array([[[2, 3, 5], [7, 11, 13]], [[17, 19, 23], [29, 31, 37]]])
array_3d

array([[[ 2,  3,  5],
        [ 7, 11, 13]],

       [[17, 19, 23],
        [29, 31, 37]]])

In [9]:
array_3d[0]

array([[ 2,  3,  5],
       [ 7, 11, 13]])

### Exercício 4

In [10]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [11]:
array_2d = np.array([[2, 3, 5], [7, 11, 13], [17, 19, 23]])
array_2d

array([[ 2,  3,  5],
       [ 7, 11, 13],
       [17, 19, 23]])

In [12]:
array_2d[2]

array([17, 19, 23])

In [13]:
array_2d[:2, 1:]

array([[ 3,  5],
       [11, 13]])

### Exercício 5

In [14]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [16]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [17]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [18]:
calc = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
calc

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [19]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [20]:
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [22]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [23]:
valores_unicos = obj.unique()
valores_unicos

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [24]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [25]:
data = resp.json()
data[0]['state']

'open'

In [26]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    37009         CLN: standardize values coercion in Blocks   
1    37008          Add pandas-genomics to the ecosystem list   
2    37006                     BLD: remove blockslider #34014   
3    37001  VIS: Allow xlabel and ylabel in DataFrame.plot...   
4    36998             BUG: DataFrame.diff with dt64 and NaTs   
5    36997  BUG/REF: read_csv shouldn't close user-provide...   
6    36995                      TYP: IntervalIndex.SetopCheck   
7    36994       TYP/REF: use OpsMixin for arithmetic methods   
8    36991     BUG: MultiIndex loses category after .stack()    
9    36990                             TYP: sas, stata, style   
10   36989                        TYP: generic, series, frame   
11   36988               DOC: Added indexing views to roadmap   
12   36985  CLN: move maybe_casted_values from pandas/core...   
13   36984  BUG: replacing a string with None causes an un...   
14   36983  BUG: Index of an empty Series cannot be compar...   
15   36982  FIX: fix cleanup warnings for errorbar timeseries   
16   36981            BUG: fix matplotlib warning on CN color   
17   36980  BUG: Pandas closes user-provided file handles ...   
18   36979  CLN: re-wrap docstrings in pandas\compat\numpy...   
19   36974  BUG: InvalidIndexError when doing fillna with ...   
20   36973  BUG: merge with MultiIndex including a Categor...   
21   36972                BUG: warning when using colors 'CN'   
22   36971  DOC: improve description of the example which ...   
23   36970  DOC: improve description of the examplewhich d...   
24   36965                         CLN: share to_native_types   
25   36961                 TYP: use OpsMixin for DecimalArray   
26   36958  DOC: Add GCS as supported filesystem for read_...   
27   36957          API: series.values EA or ndarray[object]?   
28   36956        Add optional ./ci/code_checks.sh pre-commit   
29   36955                Implement DataFrame.__array_ufunc__   

                                               labels state  
0                                                  []  open  
1                                                  []  open  
2                                                  []  open  
3   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
4                                                  []  open  
5                                                  []  open  
6                                                  []  open  
7   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
10  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
11  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
12  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
16  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
23  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
24  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
25  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
26  [{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...  open  
27  [{'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNz...  open  
28  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
29  [{'id': 47223669, 'node_id': 'MDU6TGFiZWw0NzIy...  open

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>